# List all
GET http://localhost:3000/courses/list HTTP/1.1

###

# Find One

GET http://localhost:3000/courses/2 HTTP/1.1

###

POST http://localhost:3000/courses HTTP/1.1
content-type: application/json

{
    "Parametro_fora_da_white_list":"Nao e listado",
    "name": "Novo curso",
    "description": "Wed, 21 Oct 2015 18:27:50 GMT",
    "tags": ["oleola", "asdasd"]
}

###

PATCH http://localhost:3000/courses/1 HTTP/1.1
content-type: application/json

{
    "name": "Novo curso Atualizado",
    "tags": ["asdasdsa"]
}

###

DELETE http://localhost:3000/courses/1 HTTP/1.1